

services:
  game_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    # command: /bin/bash

  game_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
    #   - ./backend:/app
    ports:
      - "3001:3001"
    # command: /bin/bash